### ISSUE TITLE
1.7 release To-Do list

### ISSUE THREAD

**Issue by draknyte1** [draknyte1/GTplusplus#151]
- [x] Fix foresty lang file.
- [x] Fix forestry crash if not present.
- [x] Fix multiblocks not working as intended.
- [x] Fix structural check for large sifter.
- [x] Fix tooltip for large sifter.
- [x] Fix scanner info for Power Substation.
- [ ] Fix issue where PSS doesnt (dis)charge batteries.
- [ ] Make a way to rebind soulbound botania items.
- [x] Ask the mystics for a solution to the ASM crash.

Read later - https://github.com/Vazkii/Botania/blob/1.7.10-final/src/main/java/vazkii/botania/common/item/relic/ItemOdinRing.java

**Comment by draknyte1** [comment]
Ask the mystics for a solution to the ASM crash.

**Comment by Dream-Master** [comment]
Enjoy your vocation not make a to-do list :)

**Comment by draknyte1** [comment]
> Fix multiblocks not working as intended. 
Possible Commits that Broke it:
https://github.com/draknyte1/GTplusplus/commit/3fdc956ccd52a9a7ecc4440ceecf89795ec2ce1b
https://github.com/draknyte1/GTplusplus/commit/c3eeecf37db4b995928f484518791e26e6804148
