### ISSUE TITLE
February To-Do List

### ISSUE THREAD

**Issue by draknyte1** [draknyte1/GTplusplus#373]
- [ ]  Add Some Custom Gendustry Frames
- [ ]  Allow changes to Gendustries power Multiplier
- [x]  Large Arc Furnace
- [x]  Void Covers
- [x]  Naquadah Reactor Mark XII
- [ ]  Grindle
- [x]  XP Convertor
- [ ]  Factory Grade Distillation Tower #363
- [ ]  Additional Information hatches for Multiblocks that output Redstone
- [ ]  Fix Handling of (Dis)Charging Busses.
- [x]  Automatic Doors
- [x]  Integrated Circuit Programming Machine
- [ ] Deep Earth Ore Drilling Rig

**Comment by draknyte1** [comment]
```
Yesterday at 13:20
PeterRabbit:
> What would be OP is a button you press that kills all hostile enemies in a large radius and teleports their drops to you
```

**Comment by draknyte1** [comment]
- [ ]  Remove Unused TC aspects
- [ ]  Fix Large Centrifuge animation
- [ ]  Query validity of Control Cores vs Energy Cores.
- [ ] Observe GTNH chat for more bugs.
